import { z } from "zod";

export const tenantStatuses = [
  "pending_activation",
  "active",
  "suspended",
  "revoked",
  "cancelled",
  "archived",
  "pending_deletion",
] as const;
export const deliveryHealthStates = ["healthy", "watch", "at-risk"] as const;
export const availabilityStates = ["available", "limited", "full"] as const;

export const tenantSchema = z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  owner: z.object({ name: z.string(), email: z.string() }),
  pendingInvitationId: z.string().nullable().optional(),
  status: z.enum(tenantStatuses),
  employeeCount: z.number().int().nonnegative(),
  clientCount: z.number().int().nonnegative(),
  createdAt: z.string(),
  usagePercent: z.number().min(0).max(100),
  tenantAdministrator: z.object({
    membershipId: z.string(),
    name: z.string(),
    email: z.string(),
    membershipStatus: z.string(),
    lastLoginAt: z.string().nullable(),
    lastLogoutAt: z.string().nullable(),
    passwordChangedAt: z.string().nullable(),
  }).nullable().optional(),
});
export type Tenant = z.infer<typeof tenantSchema>;

export const auditRecordSchema = z.object({
  id: z.string(),
  actor: z.string(),
  tenant: z.string(),
  action: z.string(),
  resource: z.string(),
  timestamp: z.string(),
  ipAddress: z.string(),
  reason: z.string(),
  reasonAutoGenerated: z.boolean(),
  result: z.enum(["success", "failed", "pending", "denied"]),
  detail: z.string(),
  summary: z.string().optional().default(""),
  employeeName: z.string().optional().default(""),
  managerName: z.string().optional().default(""),
  clientName: z.string().optional().default(""),
  resourceLabel: z.string().optional().default(""),
});
export type AuditRecord = z.infer<typeof auditRecordSchema>;

export const clientSchema = z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  currencyCode: z.string().default("INR"),
  primaryContact: z.object({ name: z.string(), email: z.string() }),
  activeServices: z.number().int().nonnegative(),
  services: z.array(z.string()),
  managers: z.array(z.string()),
  revenueAmount: z.number().nonnegative(),
  outstandingAmount: z.number().nonnegative(),
  upcomingDeadline: z.string().nullable(),
  status: z.enum(["active", "onboarding", "paused", "archived"]),
  createdAt: z.string(),
  openTasks: z.number().int().nonnegative(),
  atRiskTasks: z.number().int().nonnegative(),
  documentProgress: z.number().min(0).max(100),
});
export type Client = z.infer<typeof clientSchema>;

export const clientCreateInputSchema = z.object({
  displayName: z.string().trim().min(2, "Enter the client name.").max(160),
  legalName: z.string().trim().max(220).optional().or(z.literal("")),
  code: z.string().trim().max(40).optional().or(z.literal("")),
  primaryContact: z.object({
    name: z.string().trim().min(2, "Enter the contact name.").max(160),
    role: z.string().trim().max(160).optional().or(z.literal("")),
    email: z.string().trim().email("Enter a valid email."),
    phone: z.string().trim().max(40).optional().or(z.literal("")),
  }),
  portalAccess: z.object({
    email: z.string().trim().email("Enter a valid portal email."),
    phone: z.string().trim().max(40).optional().or(z.literal("")),
    password: z.string().min(8, "Use at least 8 characters.").max(128),
  }),
});
export type ClientCreateInput = z.infer<typeof clientCreateInputSchema>;

export const clientOptionSchema = z.object({
  id: z.string(),
  name: z.string(),
});
export type ClientOption = z.infer<typeof clientOptionSchema>;

export const clientContactSchema = z.object({
  id: z.string(),
  name: z.string(),
  role: z.string(),
  email: z.string().email(),
  phone: z.string(),
  preference: z.enum(["email", "phone", "portal"]),
  status: z.enum(["active", "archived"]),
  primary: z.boolean(),
  notes: z.string(),
});
export type ClientContact = z.infer<typeof clientContactSchema>;

export const clientContactInputSchema = clientContactSchema.omit({
  id: true,
  status: true,
});
export type ClientContactInput = z.infer<typeof clientContactInputSchema>;

export const engagementSchema = z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  service: z.string(),
  startDate: z.string(),
  endDate: z.string(),
  status: z.enum(["active", "planning", "on-hold", "complete"]),
  priority: z.enum(["high", "medium", "low"]),
  complexity: z.enum(["standard", "complex", "specialist"]),
  slaStatus: z.enum(["on-track", "watch", "at-risk"]),
  manager: z.string(),
  employees: z.number().int().nonnegative(),
  openTasks: z.number().int().nonnegative(),
  progress: z.number().min(0).max(100),
  billingModel: z.string(),
  milestones: z.array(z.string()),
});
export type ServiceEngagement = z.infer<typeof engagementSchema>;

export const clientRateItemSchema = z.object({
  id: z.string(),
  rateCardName: z.string(),
  service: z.string(),
  taskType: z.string(),
  billingUnit: z.string(),
  rateAmount: z.number(),
  currencyCode: z.string(),
  taxCode: z.string().nullable(),
  effectiveFrom: z.string(),
  effectiveTo: z.string().nullable(),
  status: z.enum(["active", "archived"]),
  tasksUsingRate: z.number().int().nonnegative(),
});
export type ClientRateItem = z.infer<typeof clientRateItemSchema>;

export const clientDetailSchema = clientSchema.extend({
  contacts: z.array(clientContactSchema),
  engagements: z.array(engagementSchema),
  workGroups: z.array(z.object({
    id: z.string(),
    name: z.string(),
    engagement: z.string(),
    manager: z.string(),
    members: z.number().int().nonnegative(),
    openTasks: z.number().int().nonnegative(),
    slaStatus: z.enum(["on-track", "watch", "at-risk"]),
    status: z.enum(["active", "on-hold", "complete"]),
  })),
  tasks: z.array(z.record(z.string(), z.unknown())),
  invoices: z.array(z.record(z.string(), z.unknown())),
  rateItems: z.array(clientRateItemSchema),
  activity: z.array(z.record(z.string(), z.unknown())),
});
export type ClientDetail = z.infer<typeof clientDetailSchema>;

export const workGroupSchema = z.object({
  id: z.string(),
  name: z.string(),
  client: z.string(),
  engagement: z.string(),
  manager: z.string(),
  members: z.number().int().nonnegative(),
  capacityPercent: z.number().min(0).max(200),
  workloadPercent: z.number().min(0).max(100),
  openTasks: z.number().int().nonnegative(),
  slaStatus: z.enum(["on-track", "watch", "at-risk"]),
  status: z.enum(["active", "on-hold", "complete"]),
});
export type WorkGroup = z.infer<typeof workGroupSchema>;

export const workGroupInputSchema = workGroupSchema.omit({ id: true });
export type WorkGroupInput = z.infer<typeof workGroupInputSchema>;

export const managerSchema = z.object({
  id: z.string(),
  name: z.string(),
  department: z.string(),
  workGroups: z.number().int().nonnegative(),
  employees: z.number().int().nonnegative(),
  clients: z.number().int().nonnegative(),
  openTasks: z.number().int().nonnegative(),
  pendingReviews: z.number().int().nonnegative(),
  teamUtilisation: z.number().min(0).max(100),
  slaPerformance: z.number().min(0).max(100),
  status: z.enum(["active", "on-leave"]),
});
export type Manager = z.infer<typeof managerSchema>;

export const legacyCreateTenantSchema = z.object({
  name: z.string().trim().min(2, "Enter the organisation name."),
  code: z
    .string()
    .trim()
    .regex(
      /^[A-Z0-9-]{3,16}$/,
      "Use 3–16 uppercase letters, numbers, or hyphens.",
    ),
  ownerName: z.string().trim().min(2, "Enter the tenant owner's name."),
  ownerEmail: z.string().trim().email("Enter a valid owner email."),
  primaryColour: z
    .string()
    .regex(/^#[0-9A-Fa-f]{6}$/, "Use a six-digit hex colour."),
  timeZone: z.string().min(1, "Choose a time zone."),
  inviteOwner: z.boolean(),
  confirm: z
    .boolean()
    .refine((value) => value, "Confirm the tenant details before continuing."),
}).extend({
  legalName: z.string().trim().max(120).optional(),
  businessEmail: z.string().trim().email("Enter a valid business email.").optional().or(z.literal("")),
  country: z.string().min(1, "Choose a country."),
  currency: z.enum(["INR", "USD", "GBP"]),
  administratorPhone: z.string().trim().max(30).optional(),
  plan: z.enum(["essential", "professional", "enterprise"]),
  billingCycle: z.enum(["monthly", "annual"]),
  userLimit: z.coerce.number().int().min(1).max(10000),
  modules: z.array(z.string()).min(1, "Select at least one enabled module."),
  sidebarColour: z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Use a six-digit hex colour."),
  defaultTheme: z.enum(["light", "dark", "system"]),
  portalSlug: z.string().trim().regex(/^[a-z0-9-]{3,40}$/, "Use 3–40 lowercase letters, numbers, or hyphens."),
  activationMethod: z.literal("invitation"),
});
export type LegacyCreateTenantInput = z.infer<typeof legacyCreateTenantSchema>;
export const createTenantSchema = z.object({
  company: z.object({
    displayName: z.string().trim().min(2, "Enter the company display name."),
    legalName: z.string().trim().min(2, "Enter the legal company name."),
    tenantCode: z.string().trim().regex(/^[A-Z0-9][A-Z0-9-]{1,30}[A-Z0-9]$/, "Use uppercase letters, numbers, or hyphens."),
    slug: z.string().trim().regex(/^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/, "Use lowercase letters, numbers, or hyphens."),
    countryCode: z.string().length(2, "Choose a country."),
    reportingCurrencyCode: z.string().length(3, "Choose a currency."),
    timezone: z.string().min(1, "Choose a timezone."),
    industry: z.string().trim().max(160).optional().or(z.literal("")),
    incorporationDate: z.string().optional().or(z.literal("")),
    registrationNumber: z.string().trim().max(160).optional().or(z.literal("")),
    taxIdentifier: z.string().trim().max(160).optional().or(z.literal("")),
  }),
  financialYear: z.object({
    source: z.enum(["COUNTRY_SUGGESTION_CONFIRMED", "CUSTOM_CONFIRMED"]),
    label: z.string().trim().min(2, "Enter the financial-year label."),
    startsOn: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Enter a start date."),
    endsOn: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Enter an end date."),
    templateId: z.string().uuid().optional().or(z.literal("")),
    overrideReason: z.string().trim().max(500).optional().or(z.literal("")),
  }),
  administratorMode: z.enum(["another_person", "myself"]).default("another_person"),
  tenantAdministrator: z.object({
    fullName: z.string().trim(),
    email: z.string().trim(),
    password: z.string(),
    phone: z.string().trim(),
  }),
  selfAccess: z.object({
    roles: z.array(z.enum(["TENANT_ADMIN", "MANAGER", "EMPLOYEE"])),
    displayTitle: z.string().trim().max(80).optional().or(z.literal("")),
  }),
  confirm: z.boolean().refine((value) => value, "Confirm the tenant details before creating."),
}).superRefine((value, context) => {
  if (value.company.countryCode === "GB" && !value.company.incorporationDate) {
    context.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["company", "incorporationDate"],
      message: "Enter the incorporation date for this United Kingdom company.",
    });
  }
  if (value.administratorMode === "another_person") {
    if (value.tenantAdministrator.fullName.trim().length < 2) {
      context.addIssue({ code: z.ZodIssueCode.custom, path: ["tenantAdministrator", "fullName"], message: "Enter the Tenant Administrator name." });
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.tenantAdministrator.email.trim())) {
      context.addIssue({ code: z.ZodIssueCode.custom, path: ["tenantAdministrator", "email"], message: "Enter a valid work email." });
    }
    if (value.tenantAdministrator.password.length < 8) {
      context.addIssue({ code: z.ZodIssueCode.custom, path: ["tenantAdministrator", "password"], message: "Use at least 8 characters for the temporary password." });
    }
    if (!value.tenantAdministrator.phone.trim()) {
      context.addIssue({ code: z.ZodIssueCode.custom, path: ["tenantAdministrator", "phone"], message: "Enter the Tenant Administrator phone number." });
    }
  }
  if (value.administratorMode === "myself" && value.selfAccess.roles.length === 0) {
    context.addIssue({
      code: z.ZodIssueCode.custom,
      path: ["selfAccess", "roles"],
      message: "Select at least one organisation role.",
    });
  }
});
export type CreateTenantInput = z.infer<typeof createTenantSchema>;

export const tenantCreationOptionsSchema = z.object({
  countries: z.array(z.object({
    countryCode: z.string(),
    name: z.string(),
    reportingCurrencyCode: z.string(),
    timezone: z.string(),
  })),
  countryCode: z.string().optional(),
  policyMode: z.string().optional(),
  suggestedFinancialYear: z.object({
    id: z.string(),
    label: z.string(),
    startsOn: z.string(),
    endsOn: z.string(),
    source: z.literal("COUNTRY_SUGGESTION"),
  }).optional(),
  suggestedYearEnds: z.array(z.string()).optional(),
  confirmationRequired: z.boolean().optional(),
  customAllowed: z.boolean().optional(),
  guidance: z.string().optional(),
});
export type TenantCreationOptions = z.infer<typeof tenantCreationOptionsSchema>;

export const createTenantResponseSchema = z.object({
  tenantId: z.string(),
  financialYearId: z.string(),
  membershipId: z.string(),
  tenantStatus: z.literal("active"),
});
export type CreateTenantResponse = z.infer<typeof createTenantResponseSchema>;

export const emailAvailabilitySchema = z.object({
  available: z.boolean(),
  reason: z.literal("EMAIL_ALREADY_EXISTS").optional(),
});
export type EmailAvailability = z.infer<typeof emailAvailabilitySchema>;

export const tenantBrandingDraftSchema = z.object({
  companyName: z.string().trim().min(2, "Enter a company name.").max(80),
  primaryColour: z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Use a six-digit hex colour."),
  sidebarColour: z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Use a six-digit hex colour."),
  surfaceColour: z.string().regex(/^#[0-9A-Fa-f]{6}$/, "Use a six-digit hex colour."),
  defaultTheme: z.enum(["light", "dark", "system", "custom"]),
  density: z.enum(["compact", "comfortable", "relaxed", "spacious"]),
  headingFont: z.enum(["System", "Arial", "Georgia", "Verdana", "Trebuchet"]),
  allowUserThemeOverride: z.boolean(),
  portalSubtitle: z.string().trim().max(120).optional(),
});
export type TenantBrandingDraft = z.infer<typeof tenantBrandingDraftSchema>;

export const paginationSchema = z.object({
  page: z.number().int().positive().default(1),
  pageSize: z.number().int().min(1).max(100).default(10),
});
export type PaginatedResponse<T> = {
  items: T[];
  page: number;
  pageSize: number;
  pageCount: number;
  totalItems: number;
};

export type TenantListRequest = z.infer<typeof paginationSchema> & {
  query?: string;
  status?: (typeof tenantStatuses)[number];
  createdAfter?: string;
  countryCode?: string;
  financialYear?: string;
  sort?: "name" | "createdAt" | "employees";
};

export const tenantListFiltersSchema = z.object({
  countries: z.array(z.string()),
  financialYears: z.array(z.object({ countryCode: z.string(), label: z.string() })),
});
export type TenantListFilters = z.infer<typeof tenantListFiltersSchema>;

export type ClientListRequest = z.infer<typeof paginationSchema> & {
  query?: string;
  status?: Client["status"];
  service?: string;
  manager?: string;
  employee?: string;
  revenueMin?: number;
  deadline?: "any" | "upcoming" | "none";
  sort?: "name" | "revenue" | "outstanding" | "deadline";
};

export type ClientListResponse = PaginatedResponse<Client> & {
  filters: {
    services: ClientOption[];
    managers: ClientOption[];
    employees: ClientOption[];
  };
};

export type AuditListRequest = z.infer<typeof paginationSchema> & {
  tenantId?: string;
  query?: string;
  result?: AuditRecord["result"];
  sort?: "timestamp" | "actor" | "tenant";
};
