insert into public.roles (code, name, scope, system_role)
values
  ('SUPER_ADMIN', 'Super Admin', 'platform', true),
  ('TENANT_OWNER', 'Tenant Owner', 'tenant', true),
  ('TENANT_ADMIN', 'Tenant Admin', 'tenant', true),
  ('FINANCE_USER', 'Finance User', 'tenant', true),
  ('HR_OPERATIONS_USER', 'HR Operations User', 'tenant', true),
  ('MANAGER', 'Manager', 'tenant', true),
  ('EMPLOYEE', 'Employee', 'tenant', true),
  ('CLIENT_USER', 'Client User', 'tenant', true)
on conflict (code) do update
set name = excluded.name,
    scope = excluded.scope,
    system_role = excluded.system_role;

insert into public.permissions (code, description, resource, action)
values
  ('tenant.read', 'Read tenant records.', 'tenant', 'read'),
  ('tenant.create', 'Create tenant records.', 'tenant', 'create'),
  ('tenant.update', 'Update tenant records.', 'tenant', 'update'),
  ('employee.read', 'Read employee records.', 'employee', 'read'),
  ('client.read', 'Read client records.', 'client', 'read'),
  ('client.create', 'Create client records.', 'client', 'create'),
  ('client.update', 'Update client records.', 'client', 'update'),
  ('client.read.assigned', 'Read assigned client records.', 'client', 'read.assigned'),
  ('engagement.manage', 'Manage service engagements.', 'engagement', 'manage'),
  ('work_group.manage', 'Manage work groups.', 'work_group', 'manage'),
  ('task.read', 'Read task records.', 'task', 'read'),
  ('task.read.assigned', 'Read assigned task records.', 'task', 'read.assigned'),
  ('task.create', 'Create task records.', 'task', 'create'),
  ('task.update.assigned_group', 'Update tasks in an assigned work group.', 'task', 'update.assigned_group'),
  ('task.update_status.assigned', 'Update assigned task status.', 'task', 'update_status.assigned'),
  ('work_log.create.self', 'Create own work logs.', 'work_log', 'create.self'),
  ('work_log.review.assigned_group', 'Review work logs in an assigned group.', 'work_log', 'review.assigned_group'),
  ('invoice.create', 'Create invoices.', 'invoice', 'create'),
  ('invoice.approve', 'Approve invoices.', 'invoice', 'approve'),
  ('invoice.send', 'Send invoices.', 'invoice', 'send'),
  ('document.read', 'Read permitted documents.', 'document', 'read'),
  ('document.publish', 'Publish permitted documents.', 'document', 'publish'),
  ('report.read', 'Read reports.', 'report', 'read'),
  ('branding.manage', 'Manage tenant branding.', 'branding', 'manage'),
  ('audit_log.read', 'Read audit logs.', 'audit_log', 'read')
on conflict (code) do update
set description = excluded.description,
    resource = excluded.resource,
    action = excluded.action;

insert into public.role_permissions (role_id, permission_id)
select r.id, p.id
from (
  values
    ('SUPER_ADMIN', 'tenant.read'),
    ('SUPER_ADMIN', 'tenant.create'),
    ('SUPER_ADMIN', 'tenant.update'),
    ('SUPER_ADMIN', 'audit_log.read'),
    ('SUPER_ADMIN', 'report.read'),
    ('TENANT_OWNER', 'tenant.read'),
    ('TENANT_OWNER', 'tenant.update'),
    ('TENANT_OWNER', 'employee.read'),
    ('TENANT_OWNER', 'client.read'),
    ('TENANT_OWNER', 'client.create'),
    ('TENANT_OWNER', 'client.update'),
    ('TENANT_OWNER', 'engagement.manage'),
    ('TENANT_OWNER', 'work_group.manage'),
    ('TENANT_OWNER', 'task.read'),
    ('TENANT_OWNER', 'task.create'),
    ('TENANT_OWNER', 'invoice.create'),
    ('TENANT_OWNER', 'invoice.approve'),
    ('TENANT_OWNER', 'invoice.send'),
    ('TENANT_OWNER', 'document.read'),
    ('TENANT_OWNER', 'document.publish'),
    ('TENANT_OWNER', 'report.read'),
    ('TENANT_OWNER', 'branding.manage'),
    ('TENANT_OWNER', 'audit_log.read'),
    ('TENANT_ADMIN', 'employee.read'),
    ('TENANT_ADMIN', 'client.read'),
    ('TENANT_ADMIN', 'client.create'),
    ('TENANT_ADMIN', 'client.update'),
    ('TENANT_ADMIN', 'engagement.manage'),
    ('TENANT_ADMIN', 'work_group.manage'),
    ('TENANT_ADMIN', 'task.read'),
    ('TENANT_ADMIN', 'task.create'),
    ('TENANT_ADMIN', 'invoice.create'),
    ('TENANT_ADMIN', 'document.read'),
    ('TENANT_ADMIN', 'document.publish'),
    ('TENANT_ADMIN', 'report.read'),
    ('FINANCE_USER', 'client.read'),
    ('FINANCE_USER', 'invoice.create'),
    ('FINANCE_USER', 'invoice.approve'),
    ('FINANCE_USER', 'invoice.send'),
    ('FINANCE_USER', 'report.read'),
    ('HR_OPERATIONS_USER', 'employee.read'),
    ('HR_OPERATIONS_USER', 'client.read'),
    ('HR_OPERATIONS_USER', 'work_group.manage'),
    ('HR_OPERATIONS_USER', 'task.read'),
    ('HR_OPERATIONS_USER', 'report.read'),
    ('MANAGER', 'client.read.assigned'),
    ('MANAGER', 'task.read.assigned'),
    ('MANAGER', 'task.create'),
    ('MANAGER', 'task.update.assigned_group'),
    ('MANAGER', 'task.update_status.assigned'),
    ('MANAGER', 'work_log.review.assigned_group'),
    ('MANAGER', 'document.read'),
    ('MANAGER', 'invoice.create'),
    ('EMPLOYEE', 'task.read.assigned'),
    ('EMPLOYEE', 'task.update_status.assigned'),
    ('EMPLOYEE', 'work_log.create.self'),
    ('EMPLOYEE', 'document.read'),
    ('CLIENT_USER', 'client.read.assigned'),
    ('CLIENT_USER', 'document.read')
) as seed(role_code, permission_code)
join public.roles r on r.code = seed.role_code
join public.permissions p on p.code = seed.permission_code
on conflict do nothing;
